config/routes.rb
Rails.application.routes.draw do
  resources :categories
=begin
  # get 'products/index'
  get 'products', to: 'products#index'
  get 'products/new', to: 'products#new', as: 'new_products'
  get 'products/:id', to: 'products#show', as: :product
  # a partir de los nombres, ruby on rails nos genera los helpers para las rutas
  get 'products/:id/edit', to: 'products#edit', as: :edit_product
  patch 'products/:id', to: 'products#update'
  post 'products', to: 'products#create'
  delete 'products/:id, to: 'products#destroy 

  La ruta destroy solo podra ser accedida con el metodo HTTP delete

  un resources creara las rutas para un CRUD completo (8 rutas) pasandole el controlador como simbolo
  Verbos HTTP    Acciones
  -get            #index
  -post           #create
  -get            #new
  -get            #edit
  -get            #show
  -patch          #update
  -put            #update
  -delete         #destroy

  El product_path sirve tanto para ver, actualizar o eliminar, el cambio es el verbo HTTP
=end

  resources :products do
    # rutas que le pertenecen a products fuera del CRUD
    # aqui le decimos que esta ruta le pertenecera a la colleccion de products como simbolo al metodo on:
    get 'search', on: :collection # al hacer esto RoR de manera automatica generara la ruta products/search -> products#search
    resources :comments, only: [:create] do # con esto RoR sabe que las rutas de comments le pertenecen a products y solo estamos creando la ruta para create
      resources :votes, only: [:create]
    end
    resources :votes, only: [:create] # con esto RoR sabe que las rutas de votes le pertenecen a products y solo estamos creando la ruta para create
  end


  root "main#welcome"
end

app/views/partials/_message.html.erb
<!-- recordar que utilizamos id porque es un identificador unico, no como una clase -->
<div class="px-6 mt-2 messages" id="message-<%= index %>">
  <div class="p-6 bg-white border-l-4 border-indigo-500 shadow-md rounded-r-lg">
    <div class="flex items-center">
      <h3 class="text-indigo-800 font-medium"><%= message %></h3>
      <button class="ml-auto message-close" value="<%= index %>">
        <svg class="text-indigo-800" width="12" height="12" viewBox="0 0 12 12" fill="none" xmlns="http://www.w3.org/2000/svg">
          <path d="M6.93341 6.00008L11.1334 1.80008C11.4001 1.53341 11.4001 1.13341 11.1334 0.866748C10.8667 0.600081 10.4667 0.600081 10.2001 0.866748L6.00008 5.06675L1.80008 0.866748C1.53341 0.600081 1.13341 0.600081 0.866748 0.866748C0.600082 1.13341 0.600082 1.53341 0.866748 1.80008L5.06675 6.00008L0.866748 10.2001C0.733415 10.3334 0.666748 10.4667 0.666748 10.6667C0.666748 11.0667 0.933415 11.3334 1.33341 11.3334C1.53341 11.3334 1.66675 11.2667 1.80008 11.1334L6.00008 6.93341L10.2001 11.1334C10.3334 11.2667 10.4667 11.3334 10.6667 11.3334C10.8667 11.3334 11.0001 11.2667 11.1334 11.1334C11.4001 10.8667 11.4001 10.4667 11.1334 10.2001L6.93341 6.00008Z" fill="currentColor"></path>
        </svg>
      </button>
    </div>
  </div>
</div>

app/views/partials/_messages.html.erb
<section>
  <%# la variable flash es la que tendra todos los mensajes que vienen del controlador %>
  <%# <% flash.each do |type, msg| - para iterar los mensajes en el flash %>
  <%# al utilizar each_with_index msg contiene dentro: typo y msg, e i el indice %>
  <%# hacemos esto para poder identificar cada boton de su mensaje con su indice %>
  <%# ya que pueden ser n mensajes dentro del flash y cada boton debe ser de su mensaje %>
  
  <% flash.each_with_index do |message, i| %>
    <%= render partial: 'partials/message', locals: {message: message[1], index: i} %>
  <% end %>
</section>

app/views/partials/_navbar.html.erb
<section class="py-8 px-4 xl:px-10">
  <nav class="relative">
    <div class="flex justify-between items-center">
      <%# link_to con bloque para imagen a root_path %>
      <%= link_to root_path do %>
          <%# image_tag 'nombre_del_archivo_en_assets_images', size:'tamaño' %>
          <%= image_tag 'logo.png', size:'50x50' %>
      <% end %>
      <div class="lg:hidden">
        <button class="navbar-burger flex items-center p-3 hover:bg-gray-50 rounded">
          <svg class="block h-4 w-4" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
            <title>Mobile menu</title>
            <path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z"></path>
          </svg>
        </button>
      </div>
      <ul class="hidden absolute top-1/2 left-1/2 transform -translate-y-1/2 -translate-x-1/2 lg:flex lg:w-auto lg:space-x-12">
        <%= link_to 'Listado de productos', root_path, class:'text-sm font-medium' %>
        <%= link_to 'Nuevo Producto', new_product_path, class:'text-sm font-medium' %>
      </ul>
      <div class="hidden lg:flex">
        <%# form_tag ya que no estamos asociando el formulario a un objeto en particular y recibe como primer argumento la ruta a la cual vamos a enviar la información y con que metodo enviaremos la info: method get %>
        <%= form_tag search_products_path, method: :get do %>
        <%# definimos el input tipo texto: nombre del input :q, enviamos el texto por los params con la llave q para recibirla en el controlador %>
          <%= text_field_tag :q, params[:q], placeholder:"Nombre del producto", class:"hidden px-4 py-3 lg:inline-block text-sm leading-normal font-medium border border-r-0 rounded-l" %>
          <%# button para el submit del form %>
          <% button_tag type:"submit" do %>
            <!-- imagen de la lupa entre las etiquetass svg -->
            <svg class="text-gray-300 w-4 h-4" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"></path>
            </svg>
          <% end %>
        <% end %>
      </div>
    </div>
  </nav>
</section>