config/routes.rb
Rails.application.routes.draw do
  resources :categories
=begin
  # get 'products/index'
  get 'products', to: 'products#index'
  get 'products/new', to: 'products#new', as: 'new_products'
  get 'products/:id', to: 'products#show', as: :product
  # a partir de los nombres, ruby on rails nos genera los helpers para las rutas
  get 'products/:id/edit', to: 'products#edit', as: :edit_product
  patch 'products/:id', to: 'products#update'
  post 'products', to: 'products#create'
  delete 'products/:id, to: 'products#destroy 

  La ruta destroy solo podra ser accedida con el metodo HTTP delete

  un resources creara las rutas para un CRUD completo (8 rutas) pasandole el controlador como simbolo
  Verbos HTTP    Acciones
  -get            #index
  -post           #create
  -get            #new
  -get            #edit
  -get            #show
  -patch          #update
  -put            #update
  -delete         #destroy

  El product_path sirve tanto para ver, actualizar o eliminar, el cambio es el verbo HTTP
=end

  resources :products do
    # rutas que le pertenecen a products fuera del CRUD
    # aqui le decimos que esta ruta le pertenecera a la colleccion de products como simbolo al metodo on:
    get 'search', on: :collection # al hacer esto RoR de manera automatica generara la ruta products/search -> products#search
    resources :comments, only: [:create] do # con esto RoR sabe que las rutas de comments le pertenecen a products y solo estamos creando la ruta para create
      resources :votes, only: [:create]
    end
    resources :votes, only: [:create] # con esto RoR sabe que las rutas de votes le pertenecen a products y solo estamos creando la ruta para create
  end


  root "main#welcome"
end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id          :integer          not null, primary key
#  nombre      :string
#  description :string
#  visible     :boolean          default(TRUE)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  slug        :string
#
class Product < ApplicationRecord
  # le indicamos a RoR que generaremos el slug del objeto a partir del campo nombre
  # annotate --models
  # Slug: string unico q reemplaza id por temas de seguridad no exponer data en la ruta-friendly_id gem
  extend FriendlyId
  friendly_id :nombre, use: :slugged

  # Valicacion: mecanismo de reglas para proteger los registros de nuestra base de datos

  # metodo validates recibe como primer argumento como simbolo el atributo a validar y despues definir el tipo de validación a aplicar
  # validates :nombre, uniqueness, length, presence, format(para regex), etc... y cada validación tiene sus metodos y argumentos para modificar

  # en el atributo errors dentro de los modelos/objetos, encontraremos todos los errores que se hayan generado a traves de las validaciónes y podemos entrar al atribudo messages para ver los errores ej: product.errors.messages #=> {:nombre => ["can't be blank"]}

  validates :nombre, presence: true
  validates :description, presence: { message: "La descripcion es requerida."}

  validates :nombre, length: {maximum: 200, minimum: 2}

  # con esto decimos que producto tendra un archivo, en este caso image y dependencia: destroy
  has_one_attached :image, :dependent => :destroy

  # relacion muchos a muchos con category por medio de product_categories
  has_many :product_categories, :dependent => :destroy
=begin
Product.last.product_categories.first.category a Product.categories

irb(main):004> Product.last.categories
  Product Load (0.3ms)  SELECT "products".* FROM "products" ORDER BY "products"."id" DESC LIMIT ?  [["LIMIT", 1]]
  Category Load (0.2ms)  SELECT "categories".* FROM "categories" INNER JOIN "product_categories" ON "categories"."id" = "product_categories"."category_id" WHERE "product_categories"."product_id" = ?  [["product_id", 101]]
=> 
[#<Category:0x000000010889c368
  id: 1,
  name: "Desarrollo de software",
  created_at: Sat, 02 Dec 2023 02:11:43.237398000 UTC +00:00,
  updated_at: Sat, 02 Dec 2023 02:11:43.237398000 UTC +00:00>]

  queremos obtener todos los categories a traves de product_categories y ActiveRecord hara internamente un join
=end
  has_many :categories, through: :product_categories # join

=begin
irb(main):015> product.categories << last_category
  TRANSACTION (0.1ms)  begin transaction
  ProductCategory Create (0.7ms)  INSERT INTO "product_categories" ("product_id", "category_id", "created_at", "updated_at") VALUES (?, ?, ?, ?)  [["product_id", 1], ["category_id", 3], ["created_at", "2023-12-02 02:27:42.013277"], ["updated_at", "2023-12-02 02:27:42.013277"]]
  TRANSACTION (0.6ms)  commit transaction
=> 
[#<Category:0x0000000108c7d720
  id: 3,
  name: "Ruby on Rails",
  created_at: Sat, 02 Dec 2023 02:11:43.239922000 UTC +00:00,
  updated_at: Sat, 02 Dec 2023 02:11:43.239922000 UTC +00:00>]
irb(main):016> 
=end 

  # indicamos que product tiene muchos comentarios
  has_many :comments, -> { order('id DESC') }, :dependent => :destroy # esto para ordenar los comentarios

  # tiene muchos votes como votable
  # Product.first.votes
  has_many :votes, as: :votable, :dependent => :destroy

  # expresiones lambda las cuales nos permiten abstraer consultas para utilizarlas en un futuro varias veces
  # metodo scope, definimos su nombre y segundo argumento la condición a traves de una expresion lmabda
  scope :visible, -> { where(visible: true) }

 # le indicamos a ActiveRecord que estamos aceptando atributos anidados de la realcion con :categories
  accepts_nested_attributes_for :categories

  def category_default
    # return self.categories.first.name if self.categories.any?
    return categories.first.name if categories.any?

    'Sin Categoria'
  end

  # metodo de clase para llamar a los productos mas populares
  def self.populars
    # hacemos un join a la tabla votes donde buscamos los productos que tengan por lo menos 1 o mas votos
    #joins(:votes)
    # hacemos un left join para incluir a productos que no tengan ni 1 solo voto
    joins("LEFT JOIN votes ON votes.votable_id = products.id AND votes.votable_type = 'Product'")
    # seleccionamos todos los campos de products y el total de votes lo guardamos en la variable total
    .select("products.*, count(votes.id) as total")
    # los agrupamos
    # .group(:product)
    .group('products.id')
    # los ordenamos por la variable total de manera descendente
    .order('total DESC')
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  # metodo que recibe un simbolo a ejecutar antes de las acciones que van dentro del parametro only pasados como simbolo
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  def index
    # pagina actual que buscaremos en los params[:page], default 1 de primera pagina y de ahi en adelante el metodo next_page avanzara y navegaremos entre las pages de pagination recibiendo el current_page como argumento del link_to y navegar
    current_page = params[:page] ||= 1
    # agregamos el metodo paginate que recibe de parametros page: pagina actual y per_page: items a mostrar
    # @products = Product.where(visible: true).order('id DESC').paginate(page: current_page, per_page: 10)
    @products = Product.populars.visible.paginate(page: current_page, per_page: 10)
  end

  def new
    # este es el @product del form_with model: @product y se guarda con el submit
    @product = Product.new
  end

  def show
  end

  def edit
  end

  def update
    if @product.update(product_params)
      redirect_to product_path(@product), notice: "El producto se actualizo de forma exitosa."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def create
    @product = Product.create(product_params)

    if @product.persisted?
      # notice es el parametro con el cual nosotros enviamos mensajes a la vista
      # helper_method: redirect_to vista/path, argumento:
      redirect_to product_path(@product), notice: "El producto se creo de forma exitosa."
    else
      #renderizamos la vista new, y con el status le hacemos saber al navegador que la peticion, no fue procesada
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    # metodo destroy busca eliminar el registro de la base de datos
    @product.destroy

    redirect_to products_path, status: :see_other, notice: 'El producto se elimino de forma exitosa.'
  end

  def search
    @q = params[:q]
    @products = Product.where("nombre LIKE ?", "%#{@q}%").where(visible: true)
  end

  private

  def set_product
    # @product = Product.find(params[:id])
    
    # de esta forma usamos la gema friendly y mostraremos su friendly en el url tomandolo del modelo aunque buscamos por detras por el id
    @product = Product.friendly.find(params[:id])
  end

  def product_params
    # category_ids seran los ids de los checkboxes como es una colleccion, se coloca asi category_ids:[]
    params.require(:product).permit(:nombre, :description, :visible, :image, category_ids:[])
  end
end

app/helpers/products_helper.rb
module ProductsHelper
  # Este se creo junto con el ProductsController y aqui colocaremos los metodos que queramos utilizar en nuestas vistas.

  def date_format(date)
    meses = %w[Enero Febrero Marzo Abril Mayo Junio Julio Agosto Septiembre Octubre Noviembre Diciembre]
    # obtenemos el mes con %-m y restamos 1 para el match con el arreglo
    mes = meses[date.strftime('%-m').to_i - 1]
    dia = date.strftime('%d')
    year = date.strftime('%Y')

    "#{dia} del #{mes} del #{year}"
  end

  def simple_description(description)
    # truncate: devolver # de caracteres especificos
    description.truncate(100)
  end
end

app/views/products/_form.html.erb
<!-- <form action=""></form> que se crea con las etiquetas html, pero no lo usaremos -->
<!-- form_tag siempre y cuando no haga referencia a un objeto de la base de datos -->
<!-- form_for formularios que hagan referencia a objetos de la base de datos -->
<!-- form_with formularios que hagan referencia a objetos de la base de datos -->
<!-- versiones actuales de Rails usar form_with, investigar mas... -->
<!-- el formulario tiene su form action="/products" method="post" -->

<!-- mediante el parametro model, definimos nuestro objeto de la base de datos model: Product.new, pero lo correcto es instanciar el product en el controller y jalarlo desde ahi -->
<%= form_with model: @product do |form| %>
  <% if @product.errors.any? %>
    <div class="mb-4">
      <% @product.errors.each do |error| %>
        <%# con el metodo full_mesage vamos a acceder al mensaje y al campo que no cumplio con alguna vadicación %>
        <li><%= error.full_message %></li>
      <% end %>
    </div>
  <% end %>

  <div class="mb-4">
    <%= form.text_field :nombre, placeholder:"Nombre del producto", class: "appearance-none block w-full py-3 px-4 text-gray-700 bg-pry-50 focus:bg-white border border-gray-200 focus:border-gray-500 rounded focus:outline-none" %>
  </div>

  <div class="mb-4">
    <%= form.text_area :description, placeholder: "Descripcion del producto", class: "appearance-none block w-full py-3 px-4 text-gray-700 bg-pry-50 focus:bg-white border border-gray-200 focus:border-gray-500 rounded focus:outline-none" %>
  </div>

  <div class="mb-4">
    <%= form.label "Visible" %>
    <%= form.check_box :visible %>
  </div>

  <div class="mb-4">
    <%= form.file_field :image %>
  </div>

  <div class="mb-4">
    <%# vamos a trabajar con una colleccion de check boxes y la enviaremos al servidor con el nombre :category_id. Pasamos la colleccion a mostrar: Category.alls y lo que enviaremos dentro de :category_ids son los :id seleccionados y en la vista mostraremos el :name %>
    <%= form.collection_check_boxes :category_ids, Category.all, :id, :name do |category| %>
      <%= category.label class:"form-check-label text-lg inline-block text-gray-600" do %>
        <%# [] Desarrollo de software [] Desarrollo movil [] Ruby on Rails %>
        <%= category.check_box + category.text %>
      <% end %>
    <% end %>
  </div>

    <div class="mb-4">
    <%= form.submit "Guardar Cambios", class: "appearance-none block w-full py-3 px-4 text-gray-700 bg-pry-50 focus:bg-white border border-gray-200 focus:border-gray-500 rounded focus:outline-none" %>
  </div>
<% end %>

app/views/products/_product.html.erb
 <div class="w-full md:w-1/2 lg:w-1/3 p-3">
    <div class="p-6 border rounded-xl">
        <div class="relative h-52 mb-6">
            <span class="absolute top-0 right-0 mt-4 mr-4 text-xs text-white px-2 py-1 font-semibold bg-gray-600 bg-opacity-100 rounded-md uppercase">
                <%= product.category_default %>
            </span>
            <% if product.image.present? %>
                <%= image_tag product.image, class:"w-full h-full object-cover rounded-lg" %> 
            <% end %>
        </div>
        <span class="inline-block mb-4 text-xs text-gray-500"><%= date_format(product.created_at) %></span>
        <h2 class="mb-4 text-2xl font-semibold font-heading"><%= product.nombre %></h2>
        <p class="mb-4 text-gray-500 leading-relaxed"><%= simple_description(product.description) %></p>
        <%# al pasarle la ruta product como lo tenemos registrado en nuestras rutas, ira directamente al show /product/:id, as: :product %>
        <%= link_to 'Conoce mas', product, class: "text-lg font-medium text-red-500 underline hover:no-underline" %>
    </div>
</div>

app/views/products/edit.html.erb
<section class="relative py-10 overflow-x-hidden">
  <div class="container">
    <h2 class="mb-6 lg:mb-10 text-4xl font-semibold font-heading">Editar producto</h2>

    <div class="relative flex flex-wrap items-center -mx-4">
      <div class="relative w-full  px-4 pb-12 lg:pb-0">
            <%= render partial:'form' %>
      </div>
  </div>
</section>

app/views/products/index.html.erb
<section class="relative">
  <div class="container px-4 mx-auto">
    <div class="max-w-3xl mb-20 mx-auto text-center">
      <h2 class="mt-8 mb-10 text-4xl font-semibold font-heading">Productos más populares 🦄</h2>
    </div>
    <div class="flex flex-wrap -m-3 mb-16">
      <%# renderizamos un parcial llamado product y con collection le decimos que por cada product que exista dentro de products, se llamara 1 parcial. 1 parcial por c/u. ej: como tarjetas. Y dentro del parcial tenemos el objeto product %>
      <%= render partial: 'product', collection: @products %>
    </div>
    <div class="text-center">
      <%# preguntamos si hay una siguiente pagina o es la ultima %>
      <% if @products.next_page.present? %>
        <%# un boton link_to pasandole de path el next page de products y si es la ultima ya no se mostrara %>
        <%# aqui @products ya viene filtrado con pagination y este trae el metodo next_page ya que ya vienen las pages armadas por pagination %>
        <%= link_to 'Ver mas productos', products_path(page: @products.next_page), class:"mb-4 px-6 py-4 text-sm text-white font-semibold bg-red-400 hover:bg-red-300 rounded transition duration-200"%>
      <% end %>
    </div>
  </div>
</section>

app/views/products/new.html.erb
<section class="relative">
    <div class="container px-4 mx-auto">
        <div class="mb-6 py-6 px-6 lg:pl-12 lg:pr-6 bg-gray-50 rounded-xl">
            <div class="flex flex-wrap -mx-4">
                <div class="w-full lg:w-2/3 px-4 mb-4 lg:mb-0">
                    <div class="max-w-xl lg:pt-6">
                        <div class="max-w-md mb-10">
                            <h2 class="text-3xl md:text-4xl font-semibold font-heading">Nuevo producto</h2>
                        </div>
                        <%= render partial: 'form' %>
                    </div>
                </div>
                <div class="w-full lg:w-1/3 px-4">
                    <div class="h-80 lg:h-40">

                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

app/views/products/search.html.erb
<section class="relative">
  <div class="container px-4 mx-auto">
    <div class="max-w-3xl mb-20 mx-auto text-center">
      <h2 class="mt-8 mb-10 text-4xl font-semibold font-heading">
        Resultado de la busqueda: <%= @q %>
      </h2>
    </div>
    <div class="flex flex-wrap -m-3 mb-16">
      <%= render partial: 'product', collection: @products %>
  </div>
</section>

app/views/products/show.html.erb
<section class="relative py-10 overflow-x-hidden">
  <div class="container  mx-auto">
    <div class="relative flex flex-wrap items-center -mx-4">
      <div class="relative w-full lg:w-1/2 px-4 pb-12 lg:pb-0">
        <h2 class="mb-6 lg:mb-10 text-4xl font-semibold font-heading">
          <%= @product.nombre %>
        </h2>
        <p class="mb-6 lg:mb-10 text-xl text-gray-500">
          <%= @product.description %>
        </p>
        <div class="mb-10 border rounded-lg">
          <% @product.categories.each do |category| %>
            <p class="font-semibold font-heading"><%= category.name %></p>
          <% end %>
        </div>
        <%= link_to 'Editar', edit_product_path(@product), class:"cursor-pointer inline-block  py-4 px-8 leading-none text-white bg-red-600 hover:bg-red-700 font-semibold rounded shadow" %>
        <%= link_to 'Eliminar', product_path(@product), data: {turbo_method: :delete, turbo_confirm: 'Estas seguro de eliminar el producto?'}, class:"cursor-pointer inline-block  py-4 px-8 leading-none text-white bg-red-600 hover:bg-red-700 font-semibold rounded shadow" %>
      </div>
      <div class="w-full lg:w-1/2 px-4">
        <% if @product.image.present? %>
          <%# helper image_tag archivo como primer parametro y estilos %>
          <%= image_tag @product.image, class:"w-full h-112 mx-auto mb-6 md:mb-0 rounded-xl object-cover" %>
        <% end %>
      </div>
    </div>
  </div>
</section>

<section>
  <small>Votos: <%= @product.votes.count %> </small>
  <div class="mb-4 mt-4">
    <%# trabajmos con rutas anidadas %>
    <%= form_with model:[@product, Vote.new] do |form| %>
      <%= form.submit "Votar 👍" , class:"cursor-pointer block lg:inline-block px-5 py-3 text-sm text-center font-semibold text-red-500 hover:text-white hover:bg-red-500 border border-red-500 hover:border-red-600 rounded transition duration-200" %>
    <% end %>
  </div>
</section>

<section>
  <div class="mb-4 mt-4">
    <%= render partial: "comments/form" %>
  </div>
</section>

<section>
  <div class="mb-4 mt-4">
    <%= render partial: "comments/comment", collection: @product.comments, as: :comment %>
  </div>
</section>